### ISSUE TITLE
Classpath File setting usage

### ISSUE THREAD

**Issue by ghost** [noseglid/java-classpath-registry#5]
I just installed your package java-import-wiz along with this package. When I use the keybind ctrl-alt-i to do an import while my cursor is over the class I'd like to import nothing happens. The keybind resolves correctly to the do-import function. I'm thinking it could be something to do with the setting "Classpath File", maybe I need to change the default on my system, but I have no idea what I'm actually suppose to enter into the box if I'd like to change the default.

I'm on Windows 10 64-bit
Atom version 1.17.2

**Comment by noseglid** [comment]
It's fine to post this here.

Contrary to how Intellij or Eclipse works, the classpath is not automatically extracted. You need to create a file (default `.classpath` in your project root) which contains the full classpath of your project. Libs provided by the java runtime are [automatically added](https://github.com/noseglid/java-classpath-registry/blob/master/lib/collector.js#L29-L39).

I've done it with a gradle task:
```
    task classpath << {
        Set deps = configurations.runtime.getFiles()
        for (set in sourceSets) {
          deps += set.runtimeClasspath;
        }

        File classpath = new File(".classpath")
        classpath.text = deps.join(':')
    }
```

In the future I want to automatically build this file from the buildtool (gradle, maven, ant, etc) so that this step will not be necessary, but until then...
